!io.github.vvb2060.magisk
!me.weishu.kernelsu
!com.kowx712.supermanager
!com.resukisu.resukisu
!com.sukisu.ultra
!me.yuki.folk
!com.sevtinge.hyperceiler
!com.tsng.hidemyapplist
!io.github.lsposed.disableflagsecure
!com.omarea.vtools
!com.skin.oplus.games
!xzr.konabess
!xzr.hkf
!me.hd.wauxv
!com.op.aod.enhance
!im.mingxi.miko
!org.frknkrc44.hma_oss
!io.github.kanotis.aodbrightplus
!com.xposed.wetypehook

?com.softwarebakery.drivedroid
?com.shizuku.uninstaller
?bin.mt.plus
?com.didjdk.adbhelper
?com.abk.kernel
?com.dere3046.checkarb
?com.nvmex.networkhelper