!/system/bin/su
!/system/xbin/su
!/system/sd/xbin/su
!/sbin/su
!/usr/bin/su
!/vendor/bin/su
!/data/local/su
!/data/local/bin/su
!/data/local/xbin/su

!/data/adb/magisk
!/data/adb/ksu
!/data/adb/apatch
!/data/adb/ksud
!/data/adb/zygisksu
!/data/adb/lspd
!/data/adb/kpm
!/data/adb/tricky_store

?/sdcard/MT2
?/sdcard/TWRP
?/sdcard/Fox

!/dev/scene
!/dev/cpuset/scene-daemon

?/dev/virtpipe-commom-yyb
?/dev/virtpipe-commom-syzs