# Kernel Name Check Patterns
# Detect any non-ASCII characters (Chinese, Emojis, etc.)
NON_ASCII:true
# Keywords (case-insensitive)
LITERAL:@
LITERAL:github
LITERAL:-git
LITERAL:coolapk

LITERAL:pandora
LITERAL:oddpods
LITERAL:yuni
LITERAL:hummingbird
LITERAL:oanpora
LITERAL:oupi
LITERAL:ongelpeats
LITERAL:haruhi
LITERAL:angelbeats